name: Release

# Controls when the action will run. 
on:
  schedule:
    - cron: "10 04 3,17 * *" # At 04:10 on day-of-month 3 and 17.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Update & install 7z
        run: sudo apt update && sudo apt-get install p7zip-full gcc -y

      - name: Extract 7z archive and setup
        run: |
          for file_comp in *.7z; do 7z x $file_comp; done;
          mkdir Compilation;
          ls -la; pwd; free; du -ha;
          git clone https://github.com/nil0x42/duplicut;
          cd duplicut/ && make;
          cd $GITHUB_WORKSPACE;

      - name: Create small wordlist
        run: |
          cat 0-9999 animal_names brands cities_world code_departement default_password departement_fr dictionnaire_fr dictionnaire_fr_small entreprise_fr food\&drink footballers fr-top1000000 fr-top20000 noms_famille_fr noms_propres pokemon_en pokemon_fr politics powerful_man powerful_woman prenoms_fr presidents_fr presidents_us pseudo religious surname_fr twitter various_leak1 various_leak2 various_leak3 various_leak4 various_leak5 various_leak6 various_leak7 various_leak8 villes_fr > Compilation/small;
          cd Compilation; ../duplicut/duplicut small -o clem9669_wordlist_small;
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on clem9669_wordlist_small.7z clem9669_wordlist_small;
          ls -lha; pwd; free; du -ha; rm small; rm clem9669_wordlist_small

      - name: Create medium wordlist
        run: |
          cat numbers-as-words 0-9999 actors adresses_fr amusement_park_fr animal_names author author_us brands cartoon chess cities_world club_sport code_departement code_name command_dos command_unix  date_ddmm date_ddmm_separator date_ddmmyy date_ddmmyy_separator date_ddmmyy_separator2 default_password departement_fr dictionnaire_de dictionnaire_en dictionnaire_es dictionnaire_fr dictionnaire_fr_small dictionnaire_it dinosaur drugs education emails entreprise_fr expression facebook_names_1 facebook_names_2 ferie films fleuves_fr food\&drink footballers fr-top1000000 fr-top20000 insults keyboard_walk_fr latin machine_names medicaments monuments music news noms_famille_fr noms_propres parfums pokemon_en pokemon_fr politics pornstars powerful_man powerful_woman prenoms_fr presidents_fr presidents_us pseudo religious series_tv_fr series_tv_us sports stars surname_fr technology twitter various_leak1 various_leak2 various_leak3 various_leak4 various_leak5 various_leak6 various_leak7 various_leak8 videogames villes_fr virus Web/decouverte.txt > Compilation/medium 
          cd Compilation; ../duplicut/duplicut medium -o clem9669_wordlist_medium;
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on clem9669_wordlist_medium.7z clem9669_wordlist_medium;
          ls -lha; pwd; free; du -ha;rm medium; rm clem9669_wordlist_medium

      - name: Create large wordlist
        run: |
          cat numbers-as-words 0-9999 actors adresses_fr amusement_park_fr animal_names antivirus author author_us brands cartoon chess cities_world club_sport code_departement code_name command_dos command_unix  date_ddmm date_ddmm_separator date_ddmmyy date_ddmmyy_separator date_ddmmyy_separator2 date_ddmmyyyy date_ddmmyyyy_separator date_ddmmyyyy_separator2 default_password departement_fr dictionnaire_de dictionnaire_en dictionnaire_es dictionnaire_fr dictionnaire_fr_small dictionnaire_it dinosaur drugs education emails entreprise_fr expression facebook_names_1 facebook_names_2 ferie films fleuves_fr food\&drink footballers fr-top1000000 fr-top20000 immatriculation insults keyboard_walk_fr keyboard_walk_us latin machine_names medicaments monuments music news noms_famille_fr noms_propres parfums phone_number_fr phone_number_fr_33 pokemon_en pokemon_fr politics pornstars powerful_man powerful_woman prenoms_fr presidents_fr presidents_us pseudo religious series_tv_fr series_tv_us sports stars surname_fr technology various_leak1 various_leak2 various_leak3 various_leak4 various_leak5 various_leak6 various_leak7 various_leak8 videogames villes_fr virus Web/decouverte.txt > Compilation/large
          cd Compilation; ../duplicut/duplicut large -o clem9669_wordlist_large;
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on clem9669_wordlist_large.7z clem9669_wordlist_large;
          ls -lha; pwd; free; du -ha;rm large; rm clem9669_wordlist_large

      - name: CHANGELOG.md
        run: |
          cd $GITHUB_WORKSPACE;
          echo '## Generated by Github Actions' >> CHANGELOG.md
          echo '`cat 0-9999 animal_names brands cities_world code_departement default_password departement_fr dictionnaire_fr dictionnaire_fr_small entreprise_fr food\&drink footballers fr-top1000000 fr-top20000 noms_famille_fr noms_propres pokemon_en pokemon_fr politics powerful_man powerful_woman prenoms_fr presidents_fr presidents_us pseudo religious surname_fr twitter various_leak1 various_leak2 various_leak3 various_leak4 various_leak5 various_leak6 various_leak7 various_leak8 villes_fr > Compilation/small;`' >> CHANGELOG.md
          echo '`cat 0-9999 actors adresses_fr amusement_park_fr animal_names author author_us brands cartoon chess cities_world club_sport code_departement code_name command_dos command_unix  date_ddmm date_ddmm_separator date_ddmmyy date_ddmmyy_separator efault_password departement_fr dictionnaire_de dictionnaire_en dictionnaire_es dictionnaire_fr dictionnaire_fr_small dictionnaire_it dinosaur drugs education emails entreprise_fr expression facebook_names_1 facebook_names_2 ferie films fleuves_fr food\&drink footballers fr-top1000000 fr-top20000 insults keyboard_walk_fr latin machine_names medicaments monuments music news noms_famille_fr noms_propres numbers-as-words parfums pokemon_en pokemon_fr politics pornstars powerful_man powerful_woman prenoms_fr presidents_fr presidents_us pseudo religious series_tv_fr series_tv_us sports stars surname_fr technology twitter various_leak1 various_leak2 various_leak3 various_leak4 various_leak5 various_leak6 various_leak7 various_leak8 videogames villes_fr virus Web/decouverte.txt > Compilation/medium`' >> CHANGELOG.md
          echo '`cat 0-9999 actors adresses_fr amusement_park_fr animal_names antivirus author author_us brands cartoon chess cities_world club_sport code_departement code_name command_dos command_unix  date_ddmm date_ddmm_separator date_ddmmyy date_ddmmyy_separator date_ddmmyyyy date_ddmmyyyy_separator default_password departement_fr dictionnaire_de dictionnaire_en dictionnaire_es dictionnaire_fr dictionnaire_fr_small dictionnaire_it dinosaur drugs education emails entreprise_fr expression facebook_names_1 facebook_names_2 ferie films fleuves_fr food\&drink footballers fr-top1000000 fr-top20000 immatriculation insults keyboard_walk_fr keyboard_walk_us latin machine_names medicaments monuments music news noms_famille_fr noms_propres numbers-as-words parfums phone_number_fr phone_number_fr_33 pokemon_en pokemon_fr politics pornstars powerful_man powerful_woman prenoms_fr presidents_fr presidents_us pseudo religious series_tv_fr series_tv_us sports stars surname_fr technology various_leak1 various_leak2 various_leak3 various_leak4 various_leak5 various_leak6 various_leak7 various_leak8 videogames villes_fr virus Web/decouverte.txt > Compilation/large`' >> CHANGELOG.md
          ls -lha; pwd; free; du -ha;

      - name: Create release
        uses: ncipollo/release-action@v1.8.6
        id: create_release
        with:
          tag: ${{ github.run_number }}
          draft: false
          prerelease: false
          bodyFile: CHANGELOG.md
          artifacts: "Compilation/*.7z"
          token: ${{ secrets.GITHUB_TOKEN }}

